/* Automation Studio generated header file */
/* Do not edit ! */

#ifndef _LIBRARIES_20231101085048_
#define _LIBRARIES_20231101085048_

__asm__(".section \".plc\"");

/* Used IEC files */
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/ArEventLog/ArEventLog.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/ArEventLog/ArEventLog.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/ArEventLog/ArEventLog.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrWStr/AsBrWStr.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrWStr/AsBrWStr.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrWStr/AsBrWStr.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10_MC/acp10_mc.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10_MC/acp10_mc.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10_MC/acp10_mc.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10man/Acp10man.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10par/Acp10par.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/NcGlobal/NcGlobal.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/NcGlobal/NcGlobal.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/NcGlobal/NcGlobal.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/asstring/asstring.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/asstring/asstring.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/asstring/asstring.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"C:/Projects/Loupe/AxisLib/src/Ar/AxisLib/Types.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"C:/Projects/Loupe/AxisLib/src/Ar/AxisLib/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"C:/Projects/Loupe/AxisLib/src/Ar/AxisLib/AxisLib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/axiserrlib/Types.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/axiserrlib/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/axiserrlib/AxisErrLib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/persist/Persist.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/persist/Persist.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/persist/Persist.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/csvfilelib/CSVFileLib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/csvfilelib/CSVFileLib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/csvfilelib/CSVFileLib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/csvfilelib/CSVFileLib_enum.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/csvfilelib/CSVFileMgr.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/csvfilelib/CSVFileMgr_HMI.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/fiowrap/FIOWrap.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/fiowrap/FIOWrap.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/fiowrap/FIOWrap.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/stringext/StringExt.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/stringext/StringExt.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/stringext/StringExt.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/HMITools.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/HMITools.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/HMITools.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/HMI_Basic.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/HMI_Basic.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/HMI_File_Browse.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/LogViewer.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/EditorControl.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/HMI_Trend.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/RecipeMgr.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/Updater.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/ringbuflib/RingBufLib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/ringbuflib/RingBufLib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/logthat/Types.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/logthat/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/logthat/LogThat.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/piper/Piper.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/piper/Piper.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/piper/Piper.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/errorlib/ErrorLib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/errorlib/ErrorLib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/errorlib/ErrorLib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/errorlib/ErrorLib_enum.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/errorlib/ErrorCollector.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/errorlib/ErrorCollector_HMI.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/vartools/VarTools.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/vartools/VarTools.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/vartools/VarTools.fun\\\" scope \\\"global\\\"\\n\"");

/* Exported library functions and function blocks */
#ifdef _OPERATOR_EXPORT
	__asm__(".ascii \"plcexport \\\"SIZEOF\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADRINST\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SHR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ROR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ROL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SHL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AND\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"XOR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"OR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"NOT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MUL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SUB\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIV\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MOVE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MAX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LIMIT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SEL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MUX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EQ\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"NE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ABS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SQRT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LOG\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EXP\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"COS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TAN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ASIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ACOS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ATAN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EXPT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TRUNC\\\" FUN\\n\"");
#endif
#ifdef _RUNTIME_EXPORT
	__asm__(".ascii \"plcexport \\\"r_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"f_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"rf_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetTime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCActionControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCAC2\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RealTan\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAtan\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAsin\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAcos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealExp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealLn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealLog\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealExpt\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAbs\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealSin\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealCos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealSqrt\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCAC3\\\" FUB\\n\"");
#endif
#ifdef _ASTIME_EXPORT
	__asm__(".ascii \"plcexport \\\"DTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"clock_ms\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDT_TO_LocalDTStructure\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LocalDT_TO_UtcDTStructure\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructure_TO_LocalDT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LocalDTStructure_TO_UtcDT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ascTIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascDTStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIMEStructure_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_TIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructure_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DTStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DiffT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DiffDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TimeDeviceGetInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DstGetInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DstGetInfoDT\\\" FUB\\n\"");
#endif
#ifdef _ASIECCON_EXPORT
	__asm__(".ascii \"plcexport \\\"swapDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_STRING\\\" FUN\\n\"");
#endif
#ifdef _SYS_LIB_EXPORT
	__asm__(".ascii \"plcexport \\\"Byte2Bit\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"Bit2Byte\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KEY_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"KEY_enadis\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_fix\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_copy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_store\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_burn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_delete\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_write\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_clr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_chr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_str\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxfatal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxread\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_fatal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_warning\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxwarning\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_release\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_attach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_delete\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIM_ticks\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIM_musec\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SW_settime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SW_gettime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RTC_settime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RTC_gettime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TMP_free\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TMP_alloc\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MEM_free\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MEM_alloc\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_release\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_attach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_cancel\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_sleep\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_exit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_freemsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_recmsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_sendmsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_name\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_allsuspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_tmp_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_tmp_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FORCE_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_ver\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_list\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_info\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SYS_battery\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYSreset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYSxinfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYS_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xlist\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_ninfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_item\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_list\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xgetval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xsetval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xgetadr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_getadr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_getval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_setval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"slMoList\\\" FUB\\n\"");
#endif
#ifdef _ASBRSTR_EXPORT
	__asm__(".ascii \"plcexport \\\"brsftoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsatof\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsatod\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsitoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsatoi\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemmove\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemcmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrlen\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcmp\\\" FUN\\n\"");
#endif
#ifdef _AREVENTLOG_EXPORT
	__asm__(".ascii \"plcexport \\\"ArEventLogCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogGetIdent\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogGetLatestRecordID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogGetPreviousRecordID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogReadDescription\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogReadErrorNumber\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogReadAddData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogReadObjectID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogMakeEventID\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogIsError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogIsWarning\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogIsInformation\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogIsSuccess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogIsCustomerArea\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogAddDataInit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogAddDataUdint\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogAddDataDint\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogAddDataString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogAddDataQuantity\\\" FUN\\n\"");
#endif
#ifdef _ASBRWSTR_EXPORT
	__asm__(".ascii \"plcexport \\\"brwcsconv\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsncpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsncat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcscat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcscmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcslen\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsncmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcscpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsrchr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcschr\\\" FUN\\n\"");
#endif
#ifdef _ACP10_MC_EXPORT
	__asm__(".ascii \"plcexport \\\"MC_AbortTrigger\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_AutCommand\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_AutControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_AutoCamDwell\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_AxisErrorCollector\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_BrakeControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_BrakeOperation\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CalcCamFromPoints\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CalcCamFromSections\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CalcPointsFromCam\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CalcSectionsFromCam\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CamIn\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CamDwell\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CamTransition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CheckAutCompensation\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CheckEndlessPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CommandError\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ConfigPowerStageCheck\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CrossCutterControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CyclicRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CyclicReadDataInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CyclicWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_DigitalCamSwitch\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_DownloadCamProfileObj\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_DownloadCamProfileData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_DownloadParSequ\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_EventMoveAbsolute\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_EventMoveAdditive\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_EventMoveVelocity\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_GearIn\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_GetCamMasterPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_GetCamSlavePosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_GetErrorText\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_GetHardwareInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_GetParIDTransferInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_HomeAcpEncoder\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitAutData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitAutEvent\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitAutPar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitAutState\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitAxisPar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitAxisSubjectPar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitCyclicRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitCyclicWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitEndlessPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitEndlessPosAcpEnc\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitMasterParIDTransfer\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitModPos\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitParList\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitParSequ\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitParTabObj\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitReceiveNetworkData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitReceiveNetworkEnc\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitReceiveParID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitSendParID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_JogVelocity\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_JogLimitPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_JogTargetPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_LimitLoad\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_LimitLoadCam\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_LoadAxisPar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MoveAbsoluteTriggStop\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MoveAdditiveTriggStop\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MoveCyclicPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MoveCyclicPositionExt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MoveCyclicVelocity\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MoveCyclicVelocityExt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MoveVelocityTriggStop\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_NetTrace\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_NetworkInit\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_Offset\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_OffsetVelocity\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_OffsetZone\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_GetParIDInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ParTrace\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ParTraceConfig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_Phasing\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MechPosDeviationComp\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_PowerMeter\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadAutPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadAxisError\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadCyclicPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadDriveStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadNetTraceStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadParID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadParIDText\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadParList\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadParTraceStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReceiveParIDOnPLC\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ResetAutPar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SaveAxisPar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SaveCamProfileObj\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SetHardwareInputs\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SetupController\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SetupFromParTabObj\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SetupInductionMotor\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SetupIsqRipple\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SetupMotorPhasing\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SetupSynchronMotor\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_Simulation\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_TouchProbe\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_VelocityControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_WriteParID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_WriteParIDText\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_CamIn\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_CamOut\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_CamTableSelect\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_DigitalCamSwitch\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_GearIn\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_GearInPos\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_GearOut\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_Halt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_Home\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_LimitLoad\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_MoveAbsolute\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_MoveAdditive\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_MoveVelocity\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_Phasing\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_Power\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadActualPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadActualTorque\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadActualVelocity\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadAxisError\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadBoolParameter\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadDigitalInput\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadDigitalOutput\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadParameter\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_Reset\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_SetOverride\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_Stop\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_TouchProbe\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_TorqueControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_TorqueControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_WriteBoolParameter\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_WriteDigitalOutput\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_WriteParameter\\\" FUB\\n\"");
#endif
#ifdef _NCGLOBAL_EXPORT
	__asm__(".ascii \"plcexport \\\"nccnccom\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncda_dir\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncda_inf\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncda_id\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncda_wr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncda_cr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncaccess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncalloc\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncaction\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncglobal_action\\\" FUN\\n\"");
#endif
#ifdef _BRSYSTEM_EXPORT
	__asm__(".ascii \"plcexport \\\"MEMInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MEMxInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SysInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RTInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TARGETInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"HWInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SysconfInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SysconfSet\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"BatteryInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"EXCInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ZYKVLenable\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"PMemGet\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"PMemPut\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"PMemSize\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ARwinWindowsInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ARwinEthWinInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RTCyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RTInit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RTExit\\\" FUN\\n\"");
#endif
#ifdef _STANDARD_EXPORT
	__asm__(".ascii \"plcexport \\\"RF_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTUD\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTD\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTU\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"F_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"R_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SR\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RS\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SEMA\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TON\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TOF\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TP\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TON_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TOF_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TP_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LEN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LEFT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RIGHT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MID\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CONCAT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INSERT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DELETE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REPLACE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FIND\\\" FUN\\n\"");
#endif
#ifdef _FILEIO_EXPORT
	__asm__(".ascii \"plcexport \\\"FileCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileReadEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileWriteEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileRename\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileTruncate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirReadEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirRename\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirDeleteEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SetAttributes\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetAttributes\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevMemInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevLink\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevUnlink\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetVolumeLabel\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetVolumeSerialNo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileIoGetSysError\\\" FUN\\n\"");
#endif
#ifdef _ASARLOG_EXPORT
	__asm__(".ascii \"plcexport \\\"AsArLogCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogClear\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogGetInfo\\\" FUB\\n\"");
#endif
#ifdef _ASSTRING_EXPORT
	__asm__(".ascii \"plcexport \\\"ftoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"atof\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"itoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"atoi\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memmove\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memcmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strlen\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcmp\\\" FUN\\n\"");
#endif
#ifdef _AXISLIB_EXPORT
	__asm__(".ascii \"plcexport \\\"AxisStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AxisReference\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AxisBasicFn_Cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AxisBasicFn_Fast\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"axisInternalFastFn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AxisRestorePosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AxisExpandLimit\\\" FUB\\n\"");
#endif
#ifdef _AXISERRLIB_EXPORT
	__asm__(".ascii \"plcexport \\\"AxisAddErrorsToCollector\\\" FUB\\n\"");
#endif
#ifdef _PERSIST_EXPORT
	__asm__(".ascii \"plcexport \\\"PersistFn_Init\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PersistFn_Cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"persistInternalMapMemory\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"persistInternalBackup\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"persistInternalRestore\\\" FUN\\n\"");
#endif
#ifdef _CSVFILELIB_EXPORT
	__asm__(".ascii \"plcexport \\\"CSVFn_Init\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CSVOpenFile_Init\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CSVFn_Cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvInitBuffer\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvClearBuffer\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvAddToBuffer\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvSetError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvExpandVar\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvProcessData\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvAddLogInfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvParseLine\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvGetVarInfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvOpenVar\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvSaveVar\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvWriteHeader\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvRemovePrefix\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvAddPrefix\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CSVFn_HMI_Cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvhmiGenerateFileListString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"csvDTOA\\\" FUN\\n\"");
#endif
#ifdef _FIOWRAP_EXPORT
	__asm__(".ascii \"plcexport \\\"FIOManageFn_Cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FIOWrapFn_Cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"fiowSetError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"fiomSetError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"fioOpenFile_Init\\\" FUN\\n\"");
#endif
#ifdef _STRINGEXT_EXPORT
	__asm__(".ascii \"plcexport \\\"lstrip\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"rstrip\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"atoui\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"uitoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ByteToHexString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HexStringToDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GenerateTimestampMS_1\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GenerateTimestampMS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GenerateTimestamp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strncat4\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ToUpper\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ToLower\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"Timestamp_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"appendArrayIndex\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SplitFileName\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"stringlcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"stringlcat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"string2wstring\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"wstring2string\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"char2wchar\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"wchar2char\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"formatString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"stringfTime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"stringpTime\\\" FUN\\n\"");
#endif
#ifdef _HMITOOLS_EXPORT
	__asm__(".ascii \"plcexport \\\"HMIFileBrowse\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ListBoxFub\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LogView_init\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LogView_cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LogView_HMI\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"Editor_fn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TrendFn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_TabControlFn_Cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_Hide\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_Show\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_Lock\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_Unlock\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_SetFocus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_ResetFocus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_OpenTouchpad\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DirectoryFub\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"EditorControl\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ControlTouch\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ControlDismiss\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"Trend_ZoomScroll\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LogViewerGetAlarmString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LogViewerCreateString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_replaceline\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_append\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_getline\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_goto\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_highlight\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_insert\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_replacemarked\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_FindCurrentTab\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FindIndexOfString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RecipeMgr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FileQueue\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetDataObjectList\\\" FUN\\n\"");
#endif
#ifdef _RINGBUFLIB_EXPORT
	__asm__(".ascii \"plcexport \\\"BufferCopyItems\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferGetItemAdr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferAddToBottom\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferAddToTop\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferRemoveBottom\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferRemoveTop\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferRemoveOffset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferBottom\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferInit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferDestroy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferClear\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferFull\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferValid\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferStatus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GetTopIndex\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GetBottomIndex\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GetNextBottomIndex\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SetStatusPointer\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GetNextTopIndex\\\" FUN\\n\"");
#endif
#ifdef _LOGTHAT_EXPORT
	__asm__(".ascii \"plcexport \\\"logDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"createLogInit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"logEventID\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"logSuccess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"logWarning\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"logError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"logInfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"logStateChange\\\" FUB\\n\"");
#endif
#ifdef _PIPER_EXPORT
	__asm__(".ascii \"plcexport \\\"Piper_fn_Cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"Piper_Module_Fub\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"Piper_setCommand\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"Piper_checkResponses\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"Piper_handleResponseState\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"Piper_PackML\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PackMLStateString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PiperStateChange\\\" FUN\\n\"");
#endif
#ifdef _ERRORLIB_EXPORT
	__asm__(".ascii \"plcexport \\\"errcolAddSourceByAddress\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolAddSourceByName\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolAddError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolAcknowledge\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ErrorCollectorFn_Init\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ErrorCollectorFn_Cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ErrorCollectorFn_HMI_Cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolInternalSetError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolIntGenerateDisplayString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolInternalAddError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolInternalLogError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolInternalLogAcknowledge\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolInternalRemoveError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolInternalRefreshHMIDisplay\\\" FUN\\n\"");
#endif
#ifdef _VARTOOLS_EXPORT
	__asm__(".ascii \"plcexport \\\"varGetInfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"varGetValue\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"varGetLrealValue\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"varGetRealValue\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"varRefresh\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"varSetValue\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"varGetVariableList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"varGetTaskList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"varPopulateMemberNames\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"varVariableWatch\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"variableBrowser\\\" FUB\\n\"");
#endif

__asm__(".previous");


#endif /* _LIBRARIES_20231101085048_ */

